<?xml version="1.0" encoding="utf-8"?><Database Name="QLBANHANGTHOITRANGTEST" Class="DBQLBanHangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NENE\ALIKUTY;Initial Catalog=QLBANHANGTHOITRANGTEST;Integrated Security=True" SettingsObjectName="QLBanHang.Properties.Settings" SettingsPropertyName="QLBANHANGTHOITRANGTESTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CAPMA_TUDONG" Member="CAPMA_TUDONGs">
    <Type Name="CAPMA_TUDONG">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KYTU" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="KYSO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TAIKHOAN" Member="TAIKHOAN1" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CHUCVU" Member="CHUCVUs">
    <Type Name="CHUCVU">
      <Column Name="MACV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD" Member="CTHDs">
    <Type Name="CTHD">
      <Column Name="SOHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPN" Member="CTPNs">
    <Type Name="CTPN">
      <Column Name="PHIEUNHAP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAMUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="SOHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAPHD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TONGTG" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCKH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DTKH" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NCC" Member="NCCs">
    <Type Name="NCC">
      <Column Name="MANCC" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCNCC" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DTNCC" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DCNVHIENTAI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DTNV" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(9)" CanBeNull="true" />
      <Column Name="NOICAPCMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYCAPCMND" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HOKHAU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MACV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="HINHANH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="TAIKHOAN_ADMIN" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU_ADMIN" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="QUYEN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="PHIEUNHAP" Member="PHIEUNHAP1" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAPPN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TONGTG" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAMUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.TABLE_CHUCVU" Method="TABLE_CHUCVU">
    <ElementType Name="TABLE_CHUCVUResult">
      <Column Name="MACV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TANG_MATUDONG" Method="TANG_MATUDONG">
    <Parameter Name="KYTU" Parameter="kYTU" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TABLE_KHACHHANG" Method="TABLE_KHACHHANG">
    <ElementType Name="TABLE_KHACHHANGResult">
      <Column Name="MAKH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCKH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DTKH" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TABLE_NHANVIEN" Method="TABLE_NHANVIEN">
    <ElementType Name="TABLE_NHANVIENResult">
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DCNVHIENTAI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DTNV" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(9)" CanBeNull="true" />
      <Column Name="NOICAPCMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYCAPCMND" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HOKHAU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MACV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="HINHANH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RETURN_KYSO" Method="RETURN_KYSO" IsComposable="true">
    <Parameter Name="KYTU" Parameter="kYTU" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
</Database>